//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanSach.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class AdminUser
    {
        [Display(Name = "User ID")]
        public int ID { get; set; }

        [Required(ErrorMessage = "UserName không duoc rong")]
        public string NameUser { get; set; }

        [Display(Name = "Vi trí")]
        public string RoleUser { get; set; }

        [Display(Name = "Mat khau")]
        [Required(ErrorMessage = "Password không duoc rong")]
        [DataType(DataType.Password)]
        public string PasswordUser { get; set; }

        [NotMapped]
        [Compare("PasswordUser")]
        [Display(Name = "Nhap lai mat khau")]
        public string ConfirmPass { get; set; }
        [NotMapped]
        public string ErrorLogin { get; set; }

    }
}
